FROM ubuntu:22.04

RUN apt-get update \
    && apt-get install -y git \
    && apt-get install -y doxygen \
    && apt-get install -y g++ \
    && apt-get install -y cmake \
    && apt-get install -y python3

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1

ENV LANG C.UTF-8

RUN apt-get install -y python3-pip
RUN pip install conan
RUN conan profile detect --force

CMD ["/bin/bash"]
